version: '3.8'

services:
  dev:
    build: .
    container_name: dev_container
    volumes:
      # Mount the /tftpboot directory; this can be helpful during development
      - /tftpboot:/tftpboot
      # Mount all of the home directory
      - /home/$(whoami):/home/$(whoami)
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/kvm:/devb/kvm
      - /dev/net/tun:/dev/net/tun
    working_dir: $PWD
    # Enter using a command that will never return; this keeps the development container running
    command: tail -F anything